version: "2"
services:
  consul:
    image: consul:1.8.3
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0

  consul-config-loader:
    build: .
    container_name: consul-config-loader
    #image: jhipster/consul-config-loader:v0.4.1
    volumes:
      - ./central-server-config/:/config
    environment:
      - CONFIG_MODE=filesystem
      #- CONFIG_MODE=git
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - ENABLE_SPRING=true
      - ENABLE_MICRONAUT=false
